apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: argocd-o11y-demo
  name: argocd-o11y-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-o11y-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-o11y-demo
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      metadata:
      containers:
      - name: prometheus-example-app
        image: sarabala1979/argocd-o11y-demo:ged
        ports:
        - name: web
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd-o11y-demo
  name: argocd-o11y-demo
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
  selector:
    app: argocd-o11y-demo